import { defineConfig } from "@playwright/test";

export default defineConfig({
  testDir: ".",
  // Ignore stale compiled JS artifacts (generated by tsc on Aug 9) so they
  // don't shadow the .ts sources or fail on tsconfig-only aliases.
  testIgnore: /\.js$/,
  timeout: 300000,
  workers: 1,
  use: {
    browserName: "chromium",
    headless: true,
    slowMo: 500,
    baseURL: "http://localhost:3100",
  },
});
