import { mkdir, readdir, copyFile, rename, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { BUILTIN_TOOL_NAMES } from "./index";
import { seedsDir, seedSubdirForMode } from "../mds/paths";

let seedRootOverride: string | null | undefined;

let copyFailureForTest: string | null | undefined;

let embeddedSeedsOverride: Record<string, string> | null | undefined;

let embeddedSeedsCache: Record<string, string> | null | undefined;

/**
 * Override the seed root for tests (e.g. a temp dir with a partial
 * `builtin-tools/` tree). Passing null simulates a compiled binary with no
 * bundled seeds. Pass nothing (undefined) to clear the override and fall back
 * to the repo seeds.
 */
export function setSeedRootForTest(root?: string | null): void {
  seedRootOverride = root;
}

/**
 * Test hook: when set to a file name, copyTree throws while copying a file
 * entry with that name, simulating a mid-copy failure. Pass nothing
 * (undefined) to clear the hook and fall back to real copying.
 */
export function setCopyFailureForTest(fileName?: string | null): void {
  copyFailureForTest = fileName;
}

/**
 * Override the embedded builtin-tools seed map for tests. Passing null
 * simulates a binary built with no embedded seeds. Pass nothing (undefined) to
 * clear the override and fall back to the real generated module.
 */
export function setEmbeddedSeedsForTest(map?: Record<string, string> | null): void {
  embeddedSeedsOverride = map;
}

function resolveSeedRoot(): string | null {
  return seedRootOverride !== undefined ? seedRootOverride : seedsDir();
}

/**
 * Load the embedded builtin-tools seed map (generated by scripts/build-prod.ts
 * for the compiled binary). In the dev source tree the generated module is an
 * empty stub, so this returns {} and seeding falls through to the repo seeds.
 */
async function loadEmbeddedSeeds(): Promise<Record<string, string>> {
  if (embeddedSeedsOverride !== undefined) return embeddedSeedsOverride ?? {};
  if (embeddedSeedsCache === undefined) {
    try {
      const mod = await import("../../generated/builtin-tools-seeds");
      embeddedSeedsCache = mod.BUILTIN_TOOLS_SEEDS ?? {};
    } catch {
      embeddedSeedsCache = {};
    }
  }
  return embeddedSeedsCache ?? {};
}

/**
 * Clone builtin tool folders from source defaults on first run.
 *
 * For every builtin tool name, if `data/tools/builtin/<name>/` does NOT exist,
 * the ENTIRE folder is copied from `seeds/{mode}/builtin-tools/<name>/`
 * (mode = "dev" for dev, "packageAndProd" otherwise). Existing folders are
 * NEVER overwritten (the data copy is authoritative). Missing seed folders are
 * skipped gracefully.
 *
 * Under a compiled binary (no repo `seeds/` on disk) the folders are extracted
 * from the embedded builtin-tools seed map instead, with the same no-overwrite
 * + temp-then-rename + partial-cleanup semantics.
 *
 * @returns the number of folders cloned.
 */
export async function seedBuiltinToolFolders(dataDir: string, mode: string): Promise<number> {
  const seedRoot = resolveSeedRoot();
  if (seedRoot) {
    return seedFromRepoRoot(dataDir, seedRoot, mode);
  }

  // Compiled binary with no bundled seeds on disk: fall back to the embedded
  // seed map (empty in dev; generated into the binary by build-prod).
  const embedded = await loadEmbeddedSeeds();
  if (Object.keys(embedded).length === 0) return 0;
  return extractBuiltinToolFoldersFromMap(embedded, dataDir);
}

/** Clone builtin tool folders from a repo `seeds/` tree on disk. */
async function seedFromRepoRoot(
  dataDir: string,
  seedRoot: string,
  mode: string
): Promise<number> {
  const seedToolsDir = join(seedRoot, seedSubdirForMode(mode), "builtin-tools");
  const builtinRoot = join(dataDir, "tools", "builtin");

  let cloned = 0;
  for (const name of BUILTIN_TOOL_NAMES) {
    const seedDir = join(seedToolsDir, name);
    if (!existsSync(seedDir)) continue; // no seed folder for this builtin — skip

    const targetDir = join(builtinRoot, name);
    if (existsSync(targetDir)) continue; // never overwrite an existing data copy

    // Copy into a temp sibling then atomically rename into place, so a
    // mid-copy failure never leaves a partial folder that a later boot would
    // treat as authoritative. On failure the temp dir is removed.
    const tmpDir = join(builtinRoot, `.${name}.tmp-${process.pid}`);
    try {
      await copyTree(seedDir, tmpDir);
      await rename(tmpDir, targetDir);
      cloned++;
    } catch (err) {
      await rm(tmpDir, { recursive: true, force: true });
      // A failed clone shouldn't take down startup — skip + report.
      console.error(
        `[seed] Failed to clone builtin tool folder '${name}': ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    }
  }
  return cloned;
}

/**
 * Clone builtin tool folders from the embedded seed map (compiled binary).
 * Same semantics as the repo-seed path: never overwrite an existing data copy,
 * write into a temp sibling then rename into place, and remove the temp on
 * failure so a partial clone is never treated as authoritative.
 */
async function extractBuiltinToolFoldersFromMap(
  map: Record<string, string>,
  dataDir: string
): Promise<number> {
  const builtinRoot = join(dataDir, "tools", "builtin");

  let cloned = 0;
  for (const name of BUILTIN_TOOL_NAMES) {
    const prefix = `${name}/`;
    const files = Object.entries(map).filter(([rel]) => rel.startsWith(prefix));
    if (files.length === 0) continue; // no embedded files for this builtin — skip

    const targetDir = join(builtinRoot, name);
    if (existsSync(targetDir)) continue; // never overwrite an existing data copy

    const tmpDir = join(builtinRoot, `.${name}.tmp-${process.pid}`);
    try {
      await mkdir(tmpDir, { recursive: true });
      for (const [relPath, b64] of files) {
        const subPath = relPath.slice(prefix.length);
        const baseName = subPath.slice(subPath.lastIndexOf("/") + 1);
        if (copyFailureForTest === baseName) {
          throw new Error(`[test] simulated copy failure for '${baseName}'`);
        }
        await writeEmbeddedFile(subPath, b64, tmpDir);
      }
      await rename(tmpDir, targetDir);
      cloned++;
    } catch (err) {
      await rm(tmpDir, { recursive: true, force: true });
      console.error(
        `[seed] Failed to extract builtin tool folder '${name}': ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    }
  }
  return cloned;
}

/** Write one embedded file, guarding against path traversal in map keys. */
async function writeEmbeddedFile(subPath: string, b64: string, destDir: string): Promise<void> {
  const parts = subPath.split("/");
  if (parts.some((p) => p === "" || p === "." || p === "..")) {
    throw new Error(`[seed] unsafe embedded seed path '${subPath}'`);
  }
  const dest = join(destDir, ...parts);
  await mkdir(dirname(dest), { recursive: true });
  await writeFile(dest, Buffer.from(b64, "base64"));
}

/** Recursively copy a directory tree (files + subdirectories). */
async function copyTree(srcDir: string, destDir: string): Promise<void> {
  await mkdir(destDir, { recursive: true });
  const entries = await readdir(srcDir, { withFileTypes: true });
  for (const entry of entries) {
    const src = join(srcDir, entry.name);
    const dest = join(destDir, entry.name);
    if (entry.isDirectory()) {
      await copyTree(src, dest);
    } else if (entry.isFile()) {
      if (copyFailureForTest === entry.name) {
        throw new Error(`[test] simulated copy failure for '${entry.name}'`);
      }
      await copyFile(src, dest);
    }
  }
}
