/**
 * Prod build: Vite frontend -> embed into backend -> single Bun executable.
 *
 * Output:
 *   ../data/prod/visual-studio-harness   (or visual-studio-harness.exe on Windows)
 * Runtime data stays in:
 *   DATA_DIR env (if set) or ../data/prod/{config.json,sessions/,logs/}
 * Never writes into source/data.
 */

import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { join, relative, extname, dirname } from "node:path";
import { existsSync } from "node:fs";

const ROOT = join(import.meta.dir, ".."); // repoSource/
const PROJECT = join(ROOT, ".."); // Visual Studio Harness/ (parent — data/ lives here)
const PROD_DATA = process.env.DATA_DIR
  ? (process.env.DATA_DIR.startsWith("/")
      ? process.env.DATA_DIR
      : join(PROJECT, process.env.DATA_DIR))
  : join(PROJECT, "data", "prod");
const PACKAGE_DIR = join(PROJECT, "data", "package");
const RUNTIME_DATA = process.env.DATA_DIR
  ? (process.env.DATA_DIR.startsWith("/")
      ? process.env.DATA_DIR
      : join(PROJECT, process.env.DATA_DIR))
  : PROD_DATA;
const BUILD_FRONTEND = join(PROD_DATA, ".build", "frontend");
const ASSETS_OUT = join(ROOT, "_backend", "src", "generated", "frontend-assets.ts");
const BINARY_NAME = process.platform === "win32" ? "visual-studio-harness.exe" : "visual-studio-harness";
const BINARY_OUT = join(process.env.PACKAGE_DIR || PACKAGE_DIR, BINARY_NAME);

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json",
  ".webmanifest": "application/manifest+json",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".map": "application/json",
  ".txt": "text/plain; charset=utf-8",
};

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

function mimeFor(file: string): string {
  return MIME[extname(file).toLowerCase()] || "application/octet-stream";
}

async function generateAssets(frontendDir: string): Promise<number> {
  const files = await walk(frontendDir);
  const entries: string[] = [];

  for (const file of files) {
    const rel = relative(frontendDir, file).split("\\").join("/");
    const urlPath = "/" + rel;
    const buf = await readFile(file);
    const b64 = buf.toString("base64");
    const mime = mimeFor(file);
    entries.push(
      `  ${JSON.stringify(urlPath)}: { mime: ${JSON.stringify(mime)}, base64: ${JSON.stringify(b64)} },`
    );
  }

  const src = `// Generated by scripts/build-prod.ts — do not edit by hand.
// ${files.length} frontend files embedded for prod binary.

export type FrontendAsset = {
  mime: string;
  base64: string;
};

export const FRONTEND_ASSETS: Record<string, FrontendAsset> = {
${entries.join("\n")}
};
`;

  await mkdir(dirname(ASSETS_OUT), { recursive: true });
  await writeFile(ASSETS_OUT, src, "utf-8");
  return files.length;
}

async function run(cmd: string[], cwd: string): Promise<void> {
  console.log(`$ ${cmd.join(" ")}`);
  const proc = Bun.spawn(cmd, {
    cwd,
    stdout: "inherit",
    stderr: "inherit",
    env: { ...process.env, MODE: "prod" },
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`Command failed (${code}): ${cmd.join(" ")}`);
  }
}

async function main() {
  const targetFlag = process.argv.find(a => a.startsWith("--target="));
  const target = targetFlag ? targetFlag.split("=")[1] : "bun";
  const typeFlag = process.argv.find(a => a.startsWith("--type="));
  const buildType = typeFlag ? typeFlag.split("=")[1] : "";
  const seedFlag = process.argv.find(a => a.startsWith("--seed="));
  const seedData = seedFlag ? seedFlag.split("=")[1] : "{}";

  if (buildType === "installer") {
    console.log("=== Installer build — building base binary first ===");
    await run(["bun", "run", "scripts/build-prod.ts", `--target=${target}`], ROOT);
    console.log("\n=== Building installer ===");
    await run(["bun", "run", "scripts/build-installer.ts", `--target=${target}`, `--seed=${seedData}`], ROOT);
    // build-installer.ts cleans up the intermediate base binary
    console.log("\n=== Installer build complete ===");
    return;
  }

  console.log("=== visual-studio-harness prod build ===");
  console.log(`Project:    ${PROJECT}`);
  console.log(`Binary:     ${BINARY_OUT}`);
  console.log(`Runtime:    ${RUNTIME_DATA}`);

  await mkdir(PROD_DATA, { recursive: true });
  await rm(BUILD_FRONTEND, { recursive: true, force: true });
  await mkdir(BUILD_FRONTEND, { recursive: true });

  // 1. Build frontend into project data/.build (not source/)
  console.log("\n[1/3] Building frontend...");
  await run(
    [
      "bun",
      "x",
      "vite",
      "build",
      "--outDir",
      BUILD_FRONTEND,
      "--emptyOutDir",
    ],
    join(ROOT, "_frontend")
  );

  // 2. Embed frontend assets into backend source
  console.log("\n[2/3] Embedding frontend assets...");
  const count = await generateAssets(BUILD_FRONTEND);
  console.log(`Embedded ${count} files into ${relative(ROOT, ASSETS_OUT)}`);

  // Derive output filename with target + type
  const targetShort = target === "bun" ? "" : target.replace(/^bun-/, "") + "-";
  const outputName = `VSH_v1.0.0-${targetShort}${buildType}`;
  const outputPath = join(process.env.PACKAGE_DIR || PACKAGE_DIR, outputName);

  // 3. Compile standalone binary into data/prod/
  console.log("\n[3/3] Compiling standalone binary...");
  if (existsSync(outputPath)) {
    await rm(outputPath, { force: true });
  }
  await run(
    [
      "bun",
      "build",
      join(ROOT, "_backend", "src", "index.ts"),
      "--compile",
      "--outfile",
      outputPath,
      "--target",
      target,
      "--define",
      "process.env.MODE=\"prod\"",
      "--define",
      `process.env.BUILD_TYPE="${buildType}"`,
    ],
    ROOT
  );

  // Reset generated assets so source tree stays clean for dev
  await writeFile(
    ASSETS_OUT,
    `// Generated by scripts/build-prod.ts — do not edit by hand.
// Empty in source tree; prod build overwrites with embedded frontend files.

export type FrontendAsset = {
  mime: string;
  base64: string;
};

export const FRONTEND_ASSETS: Record<string, FrontendAsset> = {};
`,
    "utf-8"
  );

  // Drop intermediate frontend build
  await rm(join(PROD_DATA, ".build"), { recursive: true, force: true });

  // Ensure runtime dirs exist in RUNTIME_DATA (do not wipe config/sessions)
  await mkdir(RUNTIME_DATA, { recursive: true });
  await mkdir(join(RUNTIME_DATA, "sessions"), { recursive: true });
  await mkdir(join(RUNTIME_DATA, "logs"), { recursive: true });
  if (!existsSync(join(RUNTIME_DATA, "config.json"))) {
    await writeFile(
      join(RUNTIME_DATA, "config.json"),
      JSON.stringify(
        {
          providers: [
            {
              displayName: "OpenCode Zen",
              baseUrl: "https://opencode.ai/zen/v1",
              models: [{ displayName: "Default Model", modelName: "default" }],
            },
          ],
          defaultProvider: "OpenCode Zen",
          defaultModel: "Default Model",
        },
        null,
        2
      ) + "\n"
    );
  }

  // Seed globalPerms.json if missing (runtime can also generate from hardcoded defaults).
  // Optional docs copy of the seed shape — not used at runtime for resolve.
  const permsTemplateSrc = join(
    ROOT,
    "_backend",
    "src",
    "features",
    "tools",
    "perms",
    "globalPerms.default.json"
  );
  const globalPermsOut = join(RUNTIME_DATA, "globalPerms.json");
  if (!existsSync(globalPermsOut) && existsSync(permsTemplateSrc)) {
    const templateBody = await readFile(permsTemplateSrc, "utf-8");
    await writeFile(
      globalPermsOut,
      templateBody.endsWith("\n") ? templateBody : templateBody + "\n"
    );
  }

  console.log("\n=== Build complete ===");
  console.log(`Binary: ${outputPath}`);
  console.log(`Data:   ${RUNTIME_DATA}`);
  console.log(`Run:    ${outputPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
