/**
 * Build the installer binary by embedding the portable app as base64.
 *
 * Usage:
 *   bun run scripts/build-installer.ts --target=bun-linux-x64-modern [--seed='{"mcps":[],"providers":[],"agents":[],"mds":[]}']
 *
 * Output: data/package/VSH_v1.0.0-{target-short}-installer
 */

import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";

const ROOT = join(import.meta.dir, "..");
const PROJECT = join(ROOT, "..");
const PACKAGE_DIR = join(PROJECT, "data", "package");
const GENERATED_DIR = join(ROOT, "scripts", "generated");
const DEV_DATA_DIR = join(PROJECT, "data", "dev");

const targetFlag = process.argv.find(a => a.startsWith("--target="));
const target = targetFlag ? targetFlag.split("=")[1] : "bun";
const seedFlag = process.argv.find(a => a.startsWith("--seed="));
const seedArg = seedFlag ? seedFlag.split("=")[1] : "{}";
const targetShort = target === "bun" ? "" : target.replace(/^bun-/, "") + "-";

const portableName = `VSH_v1.0.0-${targetShort}`;
const portablePath = join(PACKAGE_DIR, portableName);

async function generateSeededData(): Promise<string> {
  let seed: any = {};
  try { seed = JSON.parse(seedArg); } catch { seed = {}; }

  const devConfigPath = join(DEV_DATA_DIR, "config.json");
  let devConfig: any = {};
  try { devConfig = JSON.parse(await readFile(devConfigPath, "utf-8")); } catch {}

  const mcps: any[] = [];
  const providers: any[] = [];
  const agentConfigs: any[] = [];
  const mds: { filename: string; content: string }[] = [];

  if (seed.mcps && Array.isArray(seed.mcps) && devConfig.mcpServers) {
    for (const selected of seed.mcps) {
      const match = devConfig.mcpServers.find(
        (m: any) => m.name === selected || m.displayName === selected || JSON.stringify(m) === JSON.stringify(selected)
      );
      if (match) mcps.push(match);
    }
  }

  if (seed.providers && Array.isArray(seed.providers) && devConfig.providers) {
    for (const selected of seed.providers) {
      const match = devConfig.providers.find((p: any) => p.displayName === selected);
      if (match) providers.push(match);
    }
  }

  if (seed.agents && Array.isArray(seed.agents) && devConfig.agents) {
    for (const agentName of seed.agents) {
      const agentCfg = devConfig.agents[agentName];
      if (!agentCfg) {
        console.warn(`Warning: Agent "${agentName}" not found in config.agents`);
        continue;
      }
      const entry: any = { name: agentName };
      const cleanConfig = { ...agentCfg };
      if (cleanConfig.agentMd) {
        const path = cleanConfig.agentMd.path;
        if (path) {
          try {
            entry.agentMdContent = await readFile(path, "utf-8");
          } catch (e) {
            console.warn(`Warning: Could not read agent MD ${path}`);
          }
        }
        cleanConfig.agentMd = { mode: cleanConfig.agentMd.mode || "inline" };
      }
      if (cleanConfig.skillMds && Array.isArray(cleanConfig.skillMds)) {
        entry.skillMdContents = [];
        cleanConfig.skillMds = cleanConfig.skillMds.map((sm: any) => ({ name: sm.name, mode: sm.mode || "inline" }));
        for (const sm of agentCfg.skillMds) {
          if (sm.path) {
            try {
              entry.skillMdContents.push({ filename: sm.name || sm.path.split("/").pop(), content: await readFile(sm.path, "utf-8") });
            } catch (e) {
              console.warn(`Warning: Could not read skill MD ${sm.path}`);
            }
          }
        }
      }
      entry.config = cleanConfig;
      agentConfigs.push(entry);
    }
  }

  if (seed.mds && Array.isArray(seed.mds)) {
    for (const mdFile of seed.mds) {
      const mdPath = join(DEV_DATA_DIR, "mds", mdFile);
      try {
        const content = await readFile(mdPath, "utf-8");
        mds.push({ filename: mdFile, content });
      } catch (e) {
        console.warn(`Warning: Could not read MD ${mdPath}`);
      }
    }
  }

  const hasData = mcps.length > 0 || providers.length > 0 || agentConfigs.length > 0 || mds.length > 0;
  if (!hasData) return "";

  const serialized = `// Generated by build-installer.ts — do not edit by hand.
// Dev data seeded by the user at packaging time.

export const SEEDED_DATA = {
  mcps: ${JSON.stringify(mcps, null, 2)},
  providers: ${JSON.stringify(providers, null, 2)},
  agentConfigs: ${JSON.stringify(agentConfigs, null, 2)},
  mds: ${JSON.stringify(mds, null, 2)},
};
`;

  const seededPath = join(GENERATED_DIR, "seeded-data.ts");
  await writeFile(seededPath, serialized, "utf-8");
  console.log(`Wrote seeded data: ${seededPath}`);
  return seededPath;
}

async function main() {
  if (!existsSync(portablePath)) {
    throw new Error(`Portable binary not found at ${portablePath}. Build portable first.`);
  }

  console.log(`Reading portable binary: ${portablePath}`);
  const portableBuf = await readFile(portablePath);
  const base64 = portableBuf.toString("base64");

  await mkdir(GENERATED_DIR, { recursive: true });

  const generatedTs = `// Generated by scripts/build-installer.ts — do not edit by hand.
// Contains the portable binary as a base64-encoded constant.

export const PORTABLE_BINARY_BASE64 = ${JSON.stringify(base64)};
export const PORTABLE_SIZE = ${portableBuf.length};
`;

  const generatedPath = join(GENERATED_DIR, "embedded-portable.ts");
  await writeFile(generatedPath, generatedTs, "utf-8");
  console.log(`Wrote embedded portable: ${generatedPath} (${(portableBuf.length / 1024 / 1024).toFixed(1)} MB)`);

  const seedArgStr = seedArg;
  if (seedArgStr && seedArgStr !== "{}") {
    await generateSeededData();
  }

  const installerName = `VSH_v1.0.0-${targetShort}installer`;
  const installerPath = join(PACKAGE_DIR, installerName);

  if (existsSync(installerPath)) {
    await rm(installerPath, { force: true });
  }

  console.log(`Compiling installer: ${installerPath}`);
  const proc = Bun.spawn(
    [
      "bun",
      "build",
      join(ROOT, "scripts", "installer-wizard.ts"),
      "--compile",
      "--outfile",
      installerPath,
      "--target",
      target,
    ],
    {
      cwd: ROOT,
      stdout: "inherit",
      stderr: "inherit",
    },
  );
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`Installer build failed (${code})`);
  }

  // Clean up generated file and intermediate base binary
  await rm(generatedPath, { force: true });
  const seededPath = join(GENERATED_DIR, "seeded-data.ts");
  if (existsSync(seededPath)) await rm(seededPath, { force: true });
  const basePath = join(PACKAGE_DIR, portableName);
  if (existsSync(basePath) && basePath !== installerPath) {
    await rm(basePath, { force: true });
  }

  console.log("=== Installer build complete ===");
  console.log(`Installer: ${installerPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
