/**
 * Prod build: Vite frontend -> embed into backend -> single Bun executable.
 *
 * Output:
 *   ../data/prod/visual-studio-harness   (or visual-studio-harness.exe on Windows)
 * Runtime data stays in:
 *   DATA_DIR env (if set) or ../data/prod/{config.json,sessions/,logs/}
 * Never writes into source/data.
 *
 * 🚫  FOR AI AGENTS: NEVER run this script. It compiles the standalone binary
 *     and writes to /home/aaron/Desktop/Visual Studio Harness/data/package/.
 *     Only the user should trigger production builds manually via `bun run build`.
 */

import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { execSync } from "node:child_process";
import { join, relative, extname, dirname } from "node:path";
import { existsSync } from "node:fs";
import { VERSION } from "../_shared/version";

const ROOT = join(import.meta.dir, ".."); // repoSource/
const PROJECT = join(ROOT, ".."); // Visual Studio Harness/ (parent — data/ lives here)
const PROD_DATA = process.env.DATA_DIR
  ? (process.env.DATA_DIR.startsWith("/")
      ? process.env.DATA_DIR
      : join(PROJECT, process.env.DATA_DIR))
  : join(PROJECT, "data", "prod");
const PACKAGE_DIR = join(PROJECT, "data", "package");
const RUNTIME_DATA = process.env.DATA_DIR
  ? (process.env.DATA_DIR.startsWith("/")
      ? process.env.DATA_DIR
      : join(PROJECT, process.env.DATA_DIR))
  : PROD_DATA;
const BUILD_FRONTEND = join(PROD_DATA, ".build", "frontend");
const ASSETS_OUT = join(ROOT, "_backend", "src", "generated", "frontend-assets.ts");
const BUILTIN_TOOLS_SEEDS_OUT = join(
  ROOT,
  "_backend",
  "src",
  "generated",
  "builtin-tools-seeds.ts"
);
const BINARY_NAME = process.platform === "win32" ? "visual-studio-harness.exe" : "visual-studio-harness";
const BINARY_OUT = join(process.env.PACKAGE_DIR || PACKAGE_DIR, BINARY_NAME);

/** Resolve the exact Git commit this build is produced from (for the update indicator). */
function getBuildCommit(): string {
  try {
    return execSync("git rev-parse HEAD", { cwd: ROOT, encoding: "utf-8" }).trim();
  } catch {
    console.warn("WARNING: could not resolve git HEAD; BUILD_COMMIT will be empty.");
    return "";
  }
}

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json",
  ".webmanifest": "application/manifest+json",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".map": "application/json",
  ".txt": "text/plain; charset=utf-8",
};

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

function mimeFor(file: string): string {
  return MIME[extname(file).toLowerCase()] || "application/octet-stream";
}

async function generateAssets(frontendDir: string): Promise<number> {
  const files = await walk(frontendDir);
  const entries: string[] = [];

  for (const file of files) {
    const rel = relative(frontendDir, file).split("\\").join("/");
    const urlPath = "/" + rel;
    const buf = await readFile(file);
    const b64 = buf.toString("base64");
    const mime = mimeFor(file);
    entries.push(
      `  ${JSON.stringify(urlPath)}: { mime: ${JSON.stringify(mime)}, base64: ${JSON.stringify(b64)} },`
    );
  }

  const src = `// Generated by scripts/build-prod.ts — do not edit by hand.
// ${files.length} frontend files embedded for prod binary.

export type FrontendAsset = {
  mime: string;
  base64: string;
};

export const FRONTEND_ASSETS: Record<string, FrontendAsset> = {
${entries.join("\n")}
};
`;

  await mkdir(dirname(ASSETS_OUT), { recursive: true });
  await writeFile(ASSETS_OUT, src, "utf-8");
  return files.length;
}

/**
 * Embed the `seeds/packageAndProd/builtin-tools/` tree as a base64 file map so
 * first-run tool-folder cloning works in the compiled binary (which has no
 * repo `seeds/` on disk). Keys are paths relative to `builtin-tools/`.
 */
async function generateBuiltinToolsSeeds(): Promise<number> {
  const seedRoot = join(ROOT, "seeds", "packageAndProd", "builtin-tools");
  if (!existsSync(seedRoot)) {
    throw new Error(
      "builtin-tools seeds not found at seeds/packageAndProd/builtin-tools — builtin tools would be missing from the compiled binary"
    );
  }
  const files = await walk(seedRoot);
  const entries: string[] = [];

  for (const file of files) {
    const rel = relative(seedRoot, file).split("\\").join("/");
    const b64 = (await readFile(file)).toString("base64");
    entries.push(`  ${JSON.stringify(rel)}: ${JSON.stringify(b64)},`);
  }

  const src = `// Generated by scripts/build-prod.ts — do not edit by hand.
// ${files.length} builtin-tools seed files embedded for prod binary.

export const BUILTIN_TOOLS_SEEDS: Record<string, string> = {
${entries.join("\n")}
};
`;

  await mkdir(dirname(BUILTIN_TOOLS_SEEDS_OUT), { recursive: true });
  await writeFile(BUILTIN_TOOLS_SEEDS_OUT, src, "utf-8");
  return files.length;
}

async function run(cmd: string[], cwd: string): Promise<void> {
  console.log(`$ ${cmd.join(" ")}`);
  const proc = Bun.spawn(cmd, {
    cwd,
    stdout: "inherit",
    stderr: "inherit",
    env: { ...process.env, MODE: "prod" },
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`Command failed (${code}): ${cmd.join(" ")}`);
  }
}

/**
 * Bun appends the executable extension automatically when compiling for a
 * foreign target (e.g. `.exe` for `bun-windows-*`). Return it so file lookups,
 * stale-file cleanup, and logged paths point at the real artifact on disk.
 */
function exeSuffixForTarget(t: string): string {
  return t.startsWith("bun-windows") ? ".exe" : "";
}

/**
 * Map a bun target triple to the sqlite-vec platform package that provides the
 * native vector-search extension, plus the name of the shared lib inside it.
 * The platform packages are installed as siblings of the resolved `sqlite-vec`
 * package, e.g.:
 *   sqlite-vec-linux-x64/vec0.so
 *   sqlite-vec-windows-x64/vec0.dll
 *   sqlite-vec-darwin-arm64/vec0.dylib
 *
 * Returns null when the platform package for this target isn't installed.
 */
function vec0LibForTarget(
  vecRoot: string,
  t: string,
): { filename: string; path: string; platform: string } | null {
  const arch = t.includes("arm64") ? "arm64" : "x64";
  let platform: string;
  let filename: string;
  if (t.startsWith("bun-windows")) {
    platform = `windows-${arch}`;
    filename = "vec0.dll";
  } else if (t.startsWith("bun-darwin")) {
    platform = `darwin-${arch}`;
    filename = "vec0.dylib";
  } else {
    platform = `linux-${arch}`;
    filename = "vec0.so";
  }
  const libPath = join(vecRoot, `sqlite-vec-${platform}`, filename);
  if (existsSync(libPath)) return { filename, path: libPath, platform };

  // Fall back to a vendored copy so cross-compiles (notably Linux→Windows) work
  // even when the foreign-platform package isn't materialized by `bun install`
  // (e.g. vendor/sqlite-vec-windows-x64/vec0.dll for bun-windows-x64 targets).
  const vendored = join(ROOT, "vendor", `sqlite-vec-${platform}`, filename);
  if (existsSync(vendored)) return { filename, path: vendored, platform };

  return null;
}

async function main() {
  const targetFlag = process.argv.find(a => a.startsWith("--target="));
  const target = targetFlag ? targetFlag.split("=")[1] : "bun";
  const typeFlag = process.argv.find(a => a.startsWith("--type="));
  const buildType = typeFlag ? typeFlag.split("=")[1] : "";
  const seedFlag = process.argv.find(a => a.startsWith("--seed="));
  const seedData = seedFlag ? seedFlag.split("=")[1] : "{}";

  // Clean stale tsc output directories and caches that can shadow source files
  await rm(join(ROOT, "_shared", "dist"), { recursive: true, force: true });
  await rm(join(ROOT, "_frontend", "dist"), { recursive: true, force: true });
  await rm(join(ROOT, "_frontend", "tailwind.config.js"), { force: true });
  await rm(join(ROOT, "_frontend", "tailwind.config.js.map"), { force: true });
  await rm(join(ROOT, "_frontend", "tailwind.config.d.ts"), { force: true });
  await rm(join(ROOT, "_frontend", "tailwind.config.d.ts.map"), { force: true });
  await rm(join(ROOT, "tsconfig.tsbuildinfo"), { force: true });
  await rm(join(ROOT, "_backend", "tsconfig.tsbuildinfo"), { force: true });
  await rm(join(ROOT, "_frontend", "tsconfig.tsbuildinfo"), { force: true });

  if (buildType === "installer") {
    console.log("=== Installer build — building base binary first ===");
    await run(["bun", "run", "scripts/build-prod.ts", `--target=${target}`], ROOT);
    console.log("\n=== Building installer ===");
    await run(["bun", "run", "scripts/build-installer.ts", `--target=${target}`, `--seed=${seedData}`], ROOT);
    // build-installer.ts cleans up the intermediate base binary
    console.log("\n=== Installer build complete ===");
    return;
  }

  console.log("=== visual-studio-harness prod build ===");
  console.log(`Project:    ${PROJECT}`);
  console.log(`Binary:     ${BINARY_OUT}`);
  console.log(`Runtime:    ${RUNTIME_DATA}`);

  await mkdir(PROD_DATA, { recursive: true });
  await rm(BUILD_FRONTEND, { recursive: true, force: true });
  await mkdir(BUILD_FRONTEND, { recursive: true });

  // 1. Build frontend into project data/.build (not source/)
  console.log("\n[1/3] Building frontend...");
  await run(
    [
      "bun",
      "x",
      "vite",
      "build",
      "--outDir",
      BUILD_FRONTEND,
      "--emptyOutDir",
    ],
    join(ROOT, "_frontend")
  );

  // 2. Embed frontend assets into backend source
  console.log("\n[2/3] Embedding frontend assets...");
  const count = await generateAssets(BUILD_FRONTEND);
  console.log(`Embedded ${count} files into ${relative(ROOT, ASSETS_OUT)}`);

  // 2b. Embed sqlite-vec native extension so it works in compiled binaries.
  //     Selected by build target so cross-compiles (e.g. bun-windows-x64-modern)
  //     embed vec0.dll instead of the Linux vec0.so the host happens to have.
  const VEC0_EMBED_PATH = join(ROOT, "_backend", "src", "generated", "vec0-embed.ts");
  const vecPkg = Bun.resolveSync("sqlite-vec/package.json", join(ROOT, "_backend", "src"));
  const vecRoot = join(dirname(vecPkg), "..");
  const vec0Lib = vec0LibForTarget(vecRoot, target);
  if (vec0Lib) {
    const vec0Buf = await readFile(vec0Lib.path);
    const vec0B64 = vec0Buf.toString("base64");
    await writeFile(
      VEC0_EMBED_PATH,
      `// Generated by scripts/build-prod.ts — do not edit by hand.
// Embedded sqlite-vec native extension for compiled binary (${target}: ${vec0Lib.filename}).

export const VEC0_SO_BASE64 = ${JSON.stringify(vec0B64)};
export const VEC0_SO_FILENAME = ${JSON.stringify(vec0Lib.filename)};
`,
      "utf-8"
    );
    console.log(
      `Embedded ${vec0Lib.filename} (${(vec0Buf.length / 1024).toFixed(0)} KB) for ${target}`
    );
  } else if (!target.startsWith("bun-") || target.startsWith("bun-linux")) {
    throw new Error(
      `vec0 native lib not found for target "${target}" — vector search will be broken in the compiled binary. ` +
        "Run \"bun install\" so the matching sqlite-vec platform package is available."
    );
  } else {
    console.warn(
      `WARNING: sqlite-vec native lib not found for target "${target}". ` +
        "Vector search will be DISABLED in this build. " +
        "Install the matching platform package (e.g. \"bun add sqlite-vec-windows-x64\") to enable it."
    );
  }

  // 2c. Embed builtin-tools seeds so first-run cloning works in compiled binaries
  const seedCount = await generateBuiltinToolsSeeds();
  console.log(
    `Embedded ${seedCount} builtin-tools seed files into ${relative(ROOT, BUILTIN_TOOLS_SEEDS_OUT)}`
  );

  // Derive output filename with target + type
  const targetShort = target === "bun" ? "" : target.replace(/^bun-/, "") + "-";
  const outputName = `VSH_v${VERSION}-${targetShort}${buildType}`;
  const outputPath = join(
    process.env.PACKAGE_DIR || PACKAGE_DIR,
    outputName + exeSuffixForTarget(target)
  );

  // 3. Compile standalone binary into data/prod/
  console.log("\n[3/3] Compiling standalone binary...");
  if (existsSync(outputPath)) {
    await rm(outputPath, { force: true });
  }
  await run(
    [
      "bun",
      "build",
      join(ROOT, "_backend", "src", "index.ts"),
      "--compile",
      "--outfile",
      outputPath,
      "--target",
      target,
      "--define",
      "process.env.MODE=\"prod\"",
      "--define",
      `process.env.BUILD_TYPE="${buildType}"`,
      "--define",
      `process.env.BUILD_TIMESTAMP="${new Date().toISOString()}"`,
      "--define",
      `process.env.APP_VERSION="${VERSION}"`,
      "--define",
      `process.env.VSH_BUILD_COMMIT="${getBuildCommit()}"`,
    ],
    ROOT
  );

  // Reset generated assets so source tree stays clean for dev
  await writeFile(
    ASSETS_OUT,
    `// Generated by scripts/build-prod.ts — do not edit by hand.
// Empty in source tree; prod build overwrites with embedded frontend files.

export type FrontendAsset = {
  mime: string;
  base64: string;
};

export const FRONTEND_ASSETS: Record<string, FrontendAsset> = {};
`,
    "utf-8"
  );

  // Reset generated vec0 embed so source tree stays clean for dev
  await writeFile(
    VEC0_EMBED_PATH,
    `// Generated by scripts/build-prod.ts — do not edit by hand.
// Empty in source tree; prod build overwrites with embedded vec0.so base64.

export const VEC0_SO_BASE64 = "";
export const VEC0_SO_FILENAME = "vec0.so";
`,
    "utf-8"
  );

  // Reset generated builtin-tools seeds so source tree stays clean for dev
  await writeFile(
    BUILTIN_TOOLS_SEEDS_OUT,
    `// Generated by scripts/build-prod.ts — do not edit by hand.
// Empty in source tree; prod build overwrites with embedded builtin-tools seeds.

export const BUILTIN_TOOLS_SEEDS: Record<string, string> = {};
`,
    "utf-8"
  );

  // Drop intermediate frontend build
  await rm(join(PROD_DATA, ".build"), { recursive: true, force: true });

  // Ensure runtime dirs exist in RUNTIME_DATA (do not wipe config/sessions)
  await mkdir(RUNTIME_DATA, { recursive: true });
  await mkdir(join(RUNTIME_DATA, "sessions"), { recursive: true });
  await mkdir(join(RUNTIME_DATA, "logs"), { recursive: true });
  if (!existsSync(join(RUNTIME_DATA, "config.json"))) {
    await writeFile(
      join(RUNTIME_DATA, "config.json"),
      JSON.stringify(
        {
          providers: [
            {
              displayName: "OpenCode Zen",
              baseUrl: "https://opencode.ai/zen/v1",
              models: [{ displayName: "Default Model", modelName: "default" }],
            },
            {
              displayName: "Grok",
              baseUrl: "https://api.x.ai/v1",
              models: [
                { displayName: "Grok 4", modelName: "grok-4" },
                { displayName: "Grok 4 Fast", modelName: "grok-4-fast" },
                { displayName: "Grok 3", modelName: "grok-3" },
                { displayName: "Grok 3 Mini", modelName: "grok-3-mini" },
              ],
            },
          ],
          defaultProvider: "OpenCode Zen",
          defaultModel: "Default Model",
        },
        null,
        2
      ) + "\n"
    );
  }

  // Seed globalPerms.json if missing (runtime can also generate from hardcoded defaults).
  // Optional docs copy of the seed shape — not used at runtime for resolve.
  const permsTemplateSrc = join(
    ROOT,
    "_backend",
    "src",
    "features",
    "tools",
    "perms",
    "globalPerms.default.json"
  );
  const globalPermsOut = join(RUNTIME_DATA, "globalPerms.json");
  if (!existsSync(globalPermsOut) && existsSync(permsTemplateSrc)) {
    const templateBody = await readFile(permsTemplateSrc, "utf-8");
    await writeFile(
      globalPermsOut,
      templateBody.endsWith("\n") ? templateBody : templateBody + "\n"
    );
  }

  console.log("\n=== Build complete ===");
  console.log(`Binary: ${outputPath}`);
  console.log(`Data:   ${RUNTIME_DATA}`);
  console.log(`Run:    ${outputPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
